"""Seed data: all government + media publishers for Signal.ch Phase 0-1."""

import asyncio
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker

from app.config import settings
from app.models.publisher import Publisher

GOVERNMENT_PUBLISHERS = [
    {
        "name": "Swiss Federal Council (admin.ch)",
        "slug": "admin-ch",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.95,
        "rss_feeds": [
            {"url": "https://www.admin.ch/gov/de/start.html.rss", "language": "de", "category": "general"},
            {"url": "https://www.admin.ch/gov/fr/accueil.html.rss", "language": "fr", "category": "general"},
            {"url": "https://www.admin.ch/gov/it/pagina-iniziale.html.rss", "language": "it", "category": "general"},
        ],
        "scrape_config": {"enabled": True, "interval_minutes": 30, "respect_robots_txt": True},
    },
    {
        "name": "Swiss Parliament (Curia Vista)",
        "slug": "curia-vista",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.95,
        "api_endpoint": "https://ws.parlament.ch/odata.svc/",
        "scrape_config": {"enabled": True, "interval_minutes": 60},
    },
    {
        "name": "opendata.swiss",
        "slug": "opendata-swiss",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it", "en"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.90,
        "api_endpoint": "https://ckan.opendata.swiss/api/3/action/",
        "scrape_config": {"enabled": True, "interval_minutes": 360},
    },
    {
        "name": "Federal Statistical Office (BFS)",
        "slug": "bfs",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it", "en"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.95,
        "api_endpoint": "https://data.bfs.admin.ch/",
        "scrape_config": {"enabled": True, "interval_minutes": 60},
    },
    {
        "name": "Swiss Official Gazette of Commerce (SOGC/SHAB)",
        "slug": "sogc-shab",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.99,
        "api_endpoint": "https://www.shab.ch/",
        "scrape_config": {"enabled": True, "interval_minutes": 360},
    },
    {
        "name": "Swiss National Bank (SNB)",
        "slug": "snb",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it", "en"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.98,
        "api_endpoint": "https://data.snb.ch/",
        "scrape_config": {"enabled": True, "interval_minutes": 60},
    },
    {
        "name": "MeteoSwiss",
        "slug": "meteoswiss",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it", "en"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.95,
        "scrape_config": {"enabled": True, "interval_minutes": 15},
    },
    {
        "name": "Federal Office of Public Health (BAG)",
        "slug": "bag-health",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "rss_feeds": [],
        "scrape_config": {"enabled": True, "interval_minutes": 60},
    },
    {
        "name": "Federal Office for the Environment (BAFU)",
        "slug": "bafu-environment",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "scrape_config": {"enabled": True, "interval_minutes": 60},
    },
    {
        "name": "State Secretariat for Economic Affairs (SECO)",
        "slug": "seco-economy",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "scrape_config": {"enabled": True, "interval_minutes": 60},
    },
    {
        "name": "Swiss Federal Office of Energy (BFE)",
        "slug": "bfe-energy",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "scrape_config": {"enabled": True, "interval_minutes": 120},
    },
    {
        "name": "Federal Roads Office (ASTRA)",
        "slug": "astra-roads",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "scrape_config": {"enabled": True, "interval_minutes": 120},
    },
    {
        "name": "State Secretariat for Migration (SEM)",
        "slug": "sem-migration",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "scrape_config": {"enabled": True, "interval_minutes": 120},
    },
    {
        "name": "Federal Office of Police (fedpol)",
        "slug": "fedpol",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "scrape_config": {"enabled": True, "interval_minutes": 120},
    },
    {
        "name": "Swiss Federal Institute of Intellectual Property (IGE)",
        "slug": "ige-ip",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "scrape_config": {"enabled": True, "interval_minutes": 360},
    },
    {
        "name": "Swissmedic",
        "slug": "swissmedic",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.95,
        "scrape_config": {"enabled": True, "interval_minutes": 120},
    },
    {
        "name": "AlertSwiss",
        "slug": "alertswiss",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.99,
        "scrape_config": {"enabled": True, "interval_minutes": 1},
    },
    {
        "name": "Fedlex (Federal Law)",
        "slug": "fedlex",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.99,
        "scrape_config": {"enabled": True, "interval_minutes": 360},
    },
    {
        "name": "Entscheidsuche (Court Decisions)",
        "slug": "entscheidsuche",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.95,
        "scrape_config": {"enabled": True, "interval_minutes": 360},
    },
    {
        "name": "BFU (Swiss Council for Accident Prevention)",
        "slug": "bfu",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.93,
        "scrape_config": {"enabled": True, "interval_minutes": 360},
    },
    {
        "name": "Open Transport Data Switzerland",
        "slug": "opentransportdata",
        "publisher_type": "government_agency",
        "languages": ["de", "fr", "it", "en"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.90,
        "api_endpoint": "https://opentransportdata.swiss/",
        "scrape_config": {"enabled": True, "interval_minutes": 15},
    },
    {
        "name": "Lobbywatch",
        "slug": "lobbywatch",
        "publisher_type": "ngo",
        "languages": ["de", "fr"],
        "license_type": "public_domain",
        "license_allows_synthesis": True,
        "license_allows_full_text": True,
        "reliability_score": 0.85,
        "api_endpoint": "https://lobbywatch.ch/",
        "scrape_config": {"enabled": True, "interval_minutes": 10080},
    },
]

MEDIA_PUBLISHERS = [
    {
        "name": "SRF (Schweizer Radio und Fernsehen)",
        "slug": "srf",
        "publisher_type": "public_broadcaster",
        "media_group": "SRG SSR",
        "languages": ["de"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.88,
        "estimated_monthly_reach": 2000000,
        "rss_feeds": [{"url": "https://www.srf.ch/news/bnf/rss/1890", "language": "de", "category": "news"}],
    },
    {
        "name": "RTS (Radio Télévision Suisse)",
        "slug": "rts",
        "publisher_type": "public_broadcaster",
        "media_group": "SRG SSR",
        "languages": ["fr"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.88,
        "rss_feeds": [{"url": "https://www.rts.ch/info/rss", "language": "fr", "category": "news"}],
    },
    {
        "name": "NZZ (Neue Zürcher Zeitung)",
        "slug": "nzz",
        "publisher_type": "national_media",
        "media_group": "NZZ Media Group",
        "languages": ["de"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.90,
        "estimated_monthly_reach": 1500000,
        "rss_feeds": [{"url": "https://www.nzz.ch/recent.rss", "language": "de", "category": "general"}],
    },
    {
        "name": "Tages-Anzeiger",
        "slug": "tagesanzeiger",
        "publisher_type": "national_media",
        "media_group": "TX Group",
        "languages": ["de"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.85,
        "rss_feeds": [{"url": "https://www.tagesanzeiger.ch/rss", "language": "de", "category": "general"}],
    },
    {
        "name": "20 Minuten",
        "slug": "20min-de",
        "publisher_type": "national_media",
        "media_group": "TX Group",
        "languages": ["de"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.70,
        "estimated_monthly_reach": 4000000,
        "rss_feeds": [{"url": "https://www.20min.ch/rss/", "language": "de"}],
    },
    {
        "name": "Blick",
        "slug": "blick",
        "publisher_type": "national_media",
        "media_group": "Ringier",
        "languages": ["de"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.72,
        "estimated_monthly_reach": 3000000,
        "rss_feeds": [{"url": "https://www.blick.ch/rss", "language": "de"}],
    },
    {
        "name": "Watson",
        "slug": "watson",
        "publisher_type": "national_media",
        "media_group": "CH Media",
        "languages": ["de"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.73,
        "rss_feeds": [{"url": "https://www.watson.ch/api/1.0/rss/index.xml", "language": "de"}],
    },
    {
        "name": "Le Temps",
        "slug": "letemps",
        "publisher_type": "national_media",
        "languages": ["fr"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.88,
        "rss_feeds": [{"url": "https://www.letemps.ch/rss", "language": "fr"}],
    },
    {
        "name": "Republik",
        "slug": "republik",
        "publisher_type": "national_media",
        "languages": ["de"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.85,
        "rss_feeds": [{"url": "https://www.republik.ch/feed", "language": "de"}],
    },
    {
        "name": "Swissinfo",
        "slug": "swissinfo",
        "publisher_type": "public_broadcaster",
        "media_group": "SRG SSR",
        "languages": ["de", "fr", "it", "en"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.87,
        "rss_feeds": [
            {"url": "https://www.swissinfo.ch/eng/rss", "language": "en"},
            {"url": "https://www.swissinfo.ch/ger/rss", "language": "de"},
            {"url": "https://www.swissinfo.ch/fre/rss", "language": "fr"},
        ],
    },
    {
        "name": "20 Minutes (FR)",
        "slug": "20min-fr",
        "publisher_type": "national_media",
        "media_group": "TX Group",
        "languages": ["fr"],
        "license_type": "rss_only",
        "license_allows_synthesis": False,
        "license_allows_full_text": False,
        "reliability_score": 0.70,
        "rss_feeds": [{"url": "https://www.20minutes.ch/rss/", "language": "fr"}],
    },
]


async def seed_publishers():
    """Insert all publishers into the database (idempotent by slug)."""
    engine = create_async_engine(settings.database_url)
    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with session_factory() as session:
        all_publishers = GOVERNMENT_PUBLISHERS + MEDIA_PUBLISHERS
        for pub_data in all_publishers:
            result = await session.execute(
                select(Publisher).where(Publisher.slug == pub_data["slug"])
            )
            if result.scalar_one_or_none():
                continue

            publisher = Publisher(**pub_data)
            session.add(publisher)

        await session.commit()
        print(f"Seeded {len(all_publishers)} publishers")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed_publishers())
